name: Cargo Check

on:
  push:
  pull_request:
  schedule:
    # At 23:25 on Thursday.
    - cron: "25 23 * * 4"

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hnb-app
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run fmt
        run: cargo fmt -- --check
      - name: Run clippy
        run: cargo clippy -- --deny=warnings
      - name: Run check
        run: cargo check
